<?php
  /*
   * The global_climate_dashboard module tests out setting up a block using the block API and
   * rendering some content in the block using a renderable array.
   */

/**
 * Implements hook_init
 */
function global_climate_dashboard_init() {
  drupal_add_css(drupal_get_path('module', 'global_climate_dashboard') . "/global_climate_dashboard.css");
  drupal_add_js(drupal_get_path('module', 'global_climate_dashboard') . "/swfobject.js");
}

  /*
   * Implements hook_block_info().
   */
function global_climate_dashboard_block_info() {
  /*
   * $blocks[] Defines the blocks controlled by this module.
   */
  $blocks['global_climate_dashboard'] = array(
					  'info' => t('Global Climate Dashboard'),
  );
	
  return $blocks;
}

/*
 * Implements hook_block_configure().
 */
function global_climate_dashboard_block_configure($delta) {
  $form = array();
  switch ($delta) {
  case 'global_climate_dashboard':
    /* Variables needed
       $width
       $height
       $swf_path
       $config_path
       Set variables: variable_set($name, $value)
       Get variables: variable_get($name, $default = NULL)
       Set default (in block config form): '#default_value' => variable_get($name, $default = NULL),
    */
    $form['width'] = array(
			   '#type' => 'textfield',
			   '#title' => 'Dashboard Width',
			   '#description' => 'The pixel width for the dashboard',
			   '#default_value' => variable_get('global_climate_dashboard_width'),
			   );

    $form['height'] = array(
			    '#type' => 'textfield',
			    '#title' => 'Dashboard Height',
			    '#description' => 'The pixel height for the dashboard',
			    '#default_value' => variable_get('global_climate_dashboard_height'),
			    );

    $form['swf_path'] = array(
			      '#type' => 'textfield',
			      '#title' => 'Dashboard swf Path',
			      '#description' => 'The path to the dashboard flash swf file; if this it not an absolute url, it is interpreted relative to the Drupal installation directory',
			      '#default_value' => variable_get('global_climate_dashboard_swf_path'),
			      );

    $form['config_path'] = array(
				 '#type' => 'textfield',
				 '#title' => 'Dashboard Config Path',
				 '#description' => 'The URL of the dashboard xmlconfiguration file to load',
				 '#default_value' => variable_get('global_climate_dashboard_config_path'),
				 );
    break;
  }
  return $form;
}	

/*
 * Implements hook_block_save().
 */
function global_climate_dashboard_block_save($delta ='', $edit = array()) {
  switch ($delta) {
  case 'global_climate_dashboard':
    // Setting the dashboard variables from form values
    variable_set('global_climate_dashboard_width', $edit['width']);
    variable_set('global_climate_dashboard_height', $edit['height']);
    variable_set('global_climate_dashboard_swf_path', $edit['swf_path']);
    variable_set('global_climate_dashboard_config_path', $edit['config_path']);
    break;
  }	
}

/*
 * Implements hook_block_view().
 */
function global_climate_dashboard_block_view($delta = '') {
  switch($delta) {
  case 'global_climate_dashboard':
    $block['content'] = global_climate_dashboard_contents($delta);	
    return $block;
    break;
  }
}


/*
 * Custom function to render the 'mugl' field.
 */
function global_climate_dashboard_contents($delta) {
  switch($delta) {
  case 'global_climate_dashboard':
    // Initializing config variables
    $width = variable_get('global_climate_dashboard_width');
    $height = variable_get('global_climate_dashboard_height');
    $swf_path = variable_get('global_climate_dashboard_swf_path');
    $ppi_swf_path = drupal_get_path('module', 'global_climate_dashboard') . "/playerProductInstall.swf";
    $screenshot_path = drupal_get_path('module', 'global_climate_dashboard') . "/DashboardScreenShot.png";
    if (strpos($swf_path, '://') === false) {
      // if the swf_path is not an absolute url, prepend the drupal base path to it:
      $swf_path = base_path() . $swf_path;
    }
    $config_path = variable_get('global_climate_dashboard_config_path');

    // Returning the object to be rendered inside block
    return array('#markup' => <<<EOF
        <div id="globalClimateDashboard" class="global_climate_dashboard"><img width="940" height="570" src="$screenshot_path"></div>
       	<noscript>
            <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="$width" height="$height" id="Dashboard">
                <param name="movie" value="$swf_path" />
                <param name="quality" value="high" />
                <param name="bgcolor" value="#ffffff" />
                <param name="allowScriptAccess" value="sameDomain" />
                <param name="allowFullScreen" value="true" />
                <!--[if !IE]>-->
                <object type="application/x-shockwave-flash" data="$swf_path" width="$width" height="$height">
                    <param name="quality" value="high" />
                    <param name="bgcolor" value="#ffffff" />
                    <param name="allowScriptAccess" value="sameDomain" />
                    <param name="allowFullScreen" value="true" />
                <!--<![endif]-->
                <!--[if gte IE 6]>-->
                	<p> 
                		Either scripts and active content are not permitted to run or Adobe Flash Player version
                		10.0.0 or greater is not installed.
                	</p>
                <!--<![endif]-->
                    <a href="http://www.adobe.com/go/getflashplayer">
                        <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash Player" />
                    </a>
                <!--[if !IE]>-->
                </object>
                <!--<![endif]-->
            </object>
	    </noscript>		
        <script type="text/javascript">
            <!-- For version detection, set to min. required Flash Player version, or 0 (or 0.0.0), for no version detection. --> 
            var swfVersionStr = "10.0.0";
            <!-- To use express install, set to playerProductInstall.swf, otherwise the empty string. -->
            var xiSwfUrlStr = "$ppi_swf_path";
            var flashvars = { config : "$config_path" };
            var params = {};
            params.quality = "high";
            params.bgcolor = "#ffffff";
            params.allowscriptaccess = "sameDomain";
            params.allowfullscreen = "true";
            var attributes = {};
            attributes.id = "Dashboard";
            attributes.name = "Dashboard";
            attributes.align = "middle";
            swfobject.embedSWF(
                "$swf_path", "globalClimateDashboard", 
                "$width", "$height", 
                swfVersionStr, xiSwfUrlStr, 
                flashvars, params, attributes);
			<!-- JavaScript enabled so display the globalClimateDashboard div in case it is not replaced with a swf object. -->
			swfobject.createCSS("#globalClimateDashboard", "display:block;text-align:left;");
        </script>
EOF
		 );

    break;
  }
}
