#! /usr/bin/python

import os

def hexstring_plus_one(s):
    return s[:-6] + ( "%6x" % (int(s[-6:], 16)+1) )

class IdGenerator:
    def __init__(self):
        self.uuid  = "455fbcd9-0efe-4299-bf5a-cca808cd01d8"
        self.vuuid = "a842f720-efaf-46c0-8032-2b60702aee02"
        self.nid = 123

    def next_uuid(self):
        self.uuid = hexstring_plus_one(self.uuid)
        return self.uuid

    def next_vuuid(self):
        self.vuuid = hexstring_plus_one(self.vuuid)
        return self.vuuid

    def next_nid(self):
        self.nid = self.nid + 1
        return self.nid


class Template:
    def __init__(self, file):
        with open(file, "r") as f:
            self.template = f.read()
    def render(self, dict):
        return self.template % dict


idgen = IdGenerator()
gcd_data_tpl = Template("dev/gcd_data.tpl.json")
gcd_mugl_tpl = Template("dev/gcd_mugl.tpl.json")

def gcd_data_json(data_id, title, data_filename):
    with open(data_filename, "r") as f:
        csvtext = f.read()
    nid = idgen.next_nid()
    return gcd_data_tpl.render({
            'gcd_data_csvtext' : csvtext.replace("\n", "\\n"),
            'gcd_data_id' : data_id,
            'title' : title,
            'nid' : nid,
            'vid' : nid,
            'uuid' : idgen.next_uuid(),
            'vuuid' : idgen.next_vuuid()
            })

def gcd_mugl_json(mugl_id, title, mugl_filename):
    with open(mugl_filename, "r") as f:
        xmltext = f.read()
    nid = idgen.next_nid()
    return gcd_mugl_tpl.render({
            'gcd_mugl_xmltext' : xmltext.replace('"', '\\"').replace("\t", " ").replace("\n", "\\n"),
            'gcd_mugl_id' : mugl_id,
            'title' : title,
            'nid' : nid,
            'vid' : nid,
            'uuid' : idgen.next_uuid(),
            'vuuid' : idgen.next_vuuid()
            })

def import_mugl(mugl_id, title, mugl_filename):
    print "importing %s" % mugl_filename
    with open("file.json", "w") as f:
        f.write(gcd_mugl_json(mugl_id, title, mugl_filename))
    os.system("drush ne-import < file.json")
    os.remove("file.json")

def import_data(data_id, title, data_filename):
    print "importing %s" % data_filename
    with open("file.json", "w") as f:
        f.write(gcd_data_json(data_id, title, data_filename))
    os.system("drush ne-import < file.json")
    os.remove("file.json")


def make_json(type, id, title, filename):
    print "converting %s" % filename
    if type == "data":
        return gcd_data_json(id, title, filename)
    else:
        return gcd_mugl_json(id, title, filename)

jsons = []

#         type          id                                    title                                                  file
jsons.append(make_json("dashboard",  "dashboard2",                         "Dashboard MUGL: dashboard2",                          "./dev/data/dashboards/dashboard2.xml"))
jsons.append(make_json("dashboard",  "dashboard-oak1",                     "Dashboard MUGL: dashboard-oak1",                      "./dev/data/dashboards/dashboard-oak1.xml"))
jsons.append(make_json("dashboard",  "flat-dashboard",                     "Dashboard MUGL: flat-dashboard",                      "./dev/data/dashboards/flat-dashboard.xml"))
jsons.append(make_json("tab",        "climateChange2",                     "Dashboard Tab MUGL: climateChange2",                  "./dev/data/tabs/climateChange2.xml"))
jsons.append(make_json("tab",        "climateChange-oak1",                 "Dashboard Tab MUGL: climateChange-oak1",              "./dev/data/tabs/climateChange-oak1.xml"))
jsons.append(make_json("tab",        "climateChange",                      "Dashboard Tab MUGL: climateChange",                   "./dev/data/tabs/climateChange.xml"))
jsons.append(make_json("tab",        "climateProjections2",                "Dashboard Tab MUGL: climateProjections2",             "./dev/data/tabs/climateProjections2.xml"))
jsons.append(make_json("tab",        "climateProjections-oak1",            "Dashboard Tab MUGL: climateProjections-oak1",         "./dev/data/tabs/climateProjections-oak1.xml"))
jsons.append(make_json("tab",        "climateProjections",                 "Dashboard Tab MUGL: climateProjections",              "./dev/data/tabs/climateProjections.xml"))
jsons.append(make_json("tab",        "climateVariability2",                "Dashboard Tab MUGL: climateVariability2",             "./dev/data/tabs/climateVariability2.xml"))
jsons.append(make_json("tab",        "climateVariability-oak1",            "Dashboard Tab MUGL: climateVariability-oak1",         "./dev/data/tabs/climateVariability-oak1.xml"))
jsons.append(make_json("tab",        "climateVariability",                 "Dashboard Tab MUGL: climateVariability",              "./dev/data/tabs/climateVariability.xml"))

jsons.append(make_json("graph",      "aoi2",                               "Dashboard Graph MUGL: aoi2",                          "./dev/data/graphs/aoi2.xml"))
jsons.append(make_json("graph",      "aoi-oak1",                           "Dashboard Graph MUGL: aoi-oak1",                      "./dev/data/graphs/aoi-oak1.xml"))
jsons.append(make_json("graph",      "aoi",                                "Dashboard Graph MUGL: aoi",                           "./dev/data/graphs/aoi.xml"))
jsons.append(make_json("graph",      "asi2",                               "Dashboard Graph MUGL: asi2",                          "./dev/data/graphs/asi2.xml"))
jsons.append(make_json("graph",      "asi-oak1",                           "Dashboard Graph MUGL: asi-oak1",                      "./dev/data/graphs/asi-oak1.xml"))
jsons.append(make_json("graph",      "asi",                                "Dashboard Graph MUGL: asi",                           "./dev/data/graphs/asi.xml"))
jsons.append(make_json("graph",      "carbonDioxide2",                     "Dashboard Graph MUGL: carbonDioxide2",                "./dev/data/graphs/carbonDioxide2.xml"))
jsons.append(make_json("graph",      "carbonDioxide-oak1",                 "Dashboard Graph MUGL: carbonDioxide-oak1",            "./dev/data/graphs/carbonDioxide-oak1.xml"))
jsons.append(make_json("graph",      "carbonDioxide",                      "Dashboard Graph MUGL: carbonDioxide",                 "./dev/data/graphs/carbonDioxide.xml"))
jsons.append(make_json("graph",      "cp2",                                "Dashboard Graph MUGL: cp2",                           "./dev/data/graphs/cp2.xml"))
jsons.append(make_json("graph",      "cp-oak1",                            "Dashboard Graph MUGL: cp-oak1",                       "./dev/data/graphs/cp-oak1.xml"))
jsons.append(make_json("graph",      "cp",                                 "Dashboard Graph MUGL: cp",                            "./dev/data/graphs/cp.xml"))
jsons.append(make_json("graph",      "glacier2",                           "Dashboard Graph MUGL: glacier2",                      "./dev/data/graphs/glacier2.xml"))
jsons.append(make_json("graph",      "glacier-oak1",                       "Dashboard Graph MUGL: glacier-oak1",                  "./dev/data/graphs/glacier-oak1.xml"))
jsons.append(make_json("graph",      "glacier",                            "Dashboard Graph MUGL: glacier",                       "./dev/data/graphs/glacier.xml"))
jsons.append(make_json("graph",      "naoi2",                              "Dashboard Graph MUGL: naoi2",                         "./dev/data/graphs/naoi2.xml"))
jsons.append(make_json("graph",      "naoi-oak1",                          "Dashboard Graph MUGL: naoi-oak1",                     "./dev/data/graphs/naoi-oak1.xml"))
jsons.append(make_json("graph",      "naoi",                               "Dashboard Graph MUGL: naoi",                          "./dev/data/graphs/naoi.xml"))
jsons.append(make_json("graph",      "oceanHeat2",                         "Dashboard Graph MUGL: oceanHeat2",                    "./dev/data/graphs/oceanHeat2.xml"))
jsons.append(make_json("graph",      "oceanHeat-oak1",                     "Dashboard Graph MUGL: oceanHeat-oak1",                "./dev/data/graphs/oceanHeat-oak1.xml"))
jsons.append(make_json("graph",      "oceanHeat",                          "Dashboard Graph MUGL: oceanHeat",                     "./dev/data/graphs/oceanHeat.xml"))
jsons.append(make_json("graph",      "oni2",                               "Dashboard Graph MUGL: oni2",                          "./dev/data/graphs/oni2.xml"))
jsons.append(make_json("graph",      "oni-oak1",                           "Dashboard Graph MUGL: oni-oak1",                      "./dev/data/graphs/oni-oak1.xml"))
jsons.append(make_json("graph",      "oni",                                "Dashboard Graph MUGL: oni",                           "./dev/data/graphs/oni.xml"))
jsons.append(make_json("graph",      "pnap2",                              "Dashboard Graph MUGL: pnap2",                         "./dev/data/graphs/pnap2.xml"))
jsons.append(make_json("graph",      "pnap-oak1",                          "Dashboard Graph MUGL: pnap-oak1",                     "./dev/data/graphs/pnap-oak1.xml"))
jsons.append(make_json("graph",      "pnap",                               "Dashboard Graph MUGL: pnap",                          "./dev/data/graphs/pnap.xml"))
jsons.append(make_json("graph",      "seaLevel2",                          "Dashboard Graph MUGL: seaLevel2",                     "./dev/data/graphs/seaLevel2.xml"))
jsons.append(make_json("graph",      "seaLevel-oak1",                      "Dashboard Graph MUGL: seaLevel-oak1",                 "./dev/data/graphs/seaLevel-oak1.xml"))
jsons.append(make_json("graph",      "seaLevel",                           "Dashboard Graph MUGL: seaLevel",                      "./dev/data/graphs/seaLevel.xml"))
jsons.append(make_json("graph",      "snowCover2",                         "Dashboard Graph MUGL: snowCover2",                    "./dev/data/graphs/snowCover2.xml"))
jsons.append(make_json("graph",      "snowCover-oak1",                     "Dashboard Graph MUGL: snowCover-oak1",                "./dev/data/graphs/snowCover-oak1.xml"))
jsons.append(make_json("graph",      "snowCover",                          "Dashboard Graph MUGL: snowCover",                     "./dev/data/graphs/snowCover.xml"))
jsons.append(make_json("graph",      "soi2",                               "Dashboard Graph MUGL: soi2",                          "./dev/data/graphs/soi2.xml"))
jsons.append(make_json("graph",      "soi-oak1",                           "Dashboard Graph MUGL: soi-oak1",                      "./dev/data/graphs/soi-oak1.xml"))
jsons.append(make_json("graph",      "soi",                                "Dashboard Graph MUGL: soi",                           "./dev/data/graphs/soi.xml"))
jsons.append(make_json("graph",      "sunsEnergy2",                        "Dashboard Graph MUGL: sunsEnergy2",                   "./dev/data/graphs/sunsEnergy2.xml"))
jsons.append(make_json("graph",      "sunsEnergy-oak1",                    "Dashboard Graph MUGL: sunsEnergy-oak1",               "./dev/data/graphs/sunsEnergy-oak1.xml"))
jsons.append(make_json("graph",      "sunsEnergy",                         "Dashboard Graph MUGL: sunsEnergy",                    "./dev/data/graphs/sunsEnergy.xml"))
jsons.append(make_json("graph",      "temperature2",                       "Dashboard Graph MUGL: temperature2",                  "./dev/data/graphs/temperature2.xml"))
jsons.append(make_json("graph",      "temperature-oak1",                   "Dashboard Graph MUGL: temperature-oak1",              "./dev/data/graphs/temperature-oak1.xml"))
jsons.append(make_json("graph",      "temperature",                        "Dashboard Graph MUGL: temperature",                   "./dev/data/graphs/temperature.xml"))
jsons.append(make_json("graph",      "totalGreenhouseGas2",                "Dashboard Graph MUGL: totalGreenhouseGas2",           "./dev/data/graphs/totalGreenhouseGas2.xml"))
jsons.append(make_json("graph",      "totalGreenhouseGas-oak1",            "Dashboard Graph MUGL: totalGreenhouseGas-oak1",       "./dev/data/graphs/totalGreenhouseGas-oak1.xml"))
jsons.append(make_json("graph",      "totalGreenhouseGas",                 "Dashboard Graph MUGL: totalGreenhouseGas",            "./dev/data/graphs/totalGreenhouseGas.xml"))

jsons.append(make_json("data",       "climate_change_aggi",                "Dashboard Data: climate_change_aggi",                 "./dev/data/data/climate_change_aggi.csv"))
jsons.append(make_json("data",       "climate_change_arctic_sea_ice",      "Dashboard Data: climate_change_arctic_sea_ice",       "./dev/data/data/climate_change_arctic_sea_ice.csv"))
jsons.append(make_json("data",       "climate_change_co2",                 "Dashboard Data: climate_change_co2",                  "./dev/data/data/climate_change_co2.csv"))
jsons.append(make_json("data",       "climate_change_glacier_ice_mass",    "Dashboard Data: climate_change_glacier_ice_mass",     "./dev/data/data/climate_change_glacier_ice_mass.csv"))
jsons.append(make_json("data",       "climate_change_ocean_heat_content",  "Dashboard Data: climate_change_ocean_heat_content",   "./dev/data/data/climate_change_ocean_heat_content.csv"))
jsons.append(make_json("data",       "climate_change_sea_level",           "Dashboard Data: climate_change_sea_level",            "./dev/data/data/climate_change_sea_level.csv"))
jsons.append(make_json("data",       "climate_change_snow_cover",          "Dashboard Data: climate_change_snow_cover",           "./dev/data/data/climate_change_snow_cover.csv"))
jsons.append(make_json("data",       "climate_change_sun_energy",          "Dashboard Data: climate_change_sun_energy",           "./dev/data/data/climate_change_sun_energy.csv"))
jsons.append(make_json("data",       "climate_change_temperature",         "Dashboard Data: climate_change_temperature",          "./dev/data/data/climate_change_temperature.csv"))
jsons.append(make_json("data",       "climate_projections_20c3m",          "Dashboard Data: climate_projections_20c3m",           "./dev/data/data/climate_projections_20c3m.csv"))
jsons.append(make_json("data",       "climate_projections2_20c3m",         "Dashboard Data: climate_projections2_20c3m",          "./dev/data/data/climate_projections2_20c3m.csv"))
jsons.append(make_json("data",       "climate_projections2_a1b",           "Dashboard Data: climate_projections2_a1b",            "./dev/data/data/climate_projections2_a1b.csv"))
jsons.append(make_json("data",       "climate_projections2_a2",            "Dashboard Data: climate_projections2_a2",             "./dev/data/data/climate_projections2_a2.csv"))
jsons.append(make_json("data",       "climate_projections2_b1",            "Dashboard Data: climate_projections2_b1",             "./dev/data/data/climate_projections2_b1.csv"))
jsons.append(make_json("data",       "climate_projections_a1b",            "Dashboard Data: climate_projections_a1b",             "./dev/data/data/climate_projections_a1b.csv"))
jsons.append(make_json("data",       "climate_projections_a2",             "Dashboard Data: climate_projections_a2",              "./dev/data/data/climate_projections_a2.csv"))
jsons.append(make_json("data",       "climate_projections_b1",             "Dashboard Data: climate_projections_b1",              "./dev/data/data/climate_projections_b1.csv"))
jsons.append(make_json("data",       "climate_vari_AO",                    "Dashboard Data: climate_vari_AO",                     "./dev/data/data/climate_vari_AO.csv"))
jsons.append(make_json("data",       "climate_vari_NAO",                   "Dashboard Data: climate_vari_NAO",                    "./dev/data/data/climate_vari_NAO.csv"))
jsons.append(make_json("data",       "climate_vari_ONI",                   "Dashboard Data: climate_vari_ONI",                    "./dev/data/data/climate_vari_ONI.csv"))
jsons.append(make_json("data",       "climate_vari_PNA",                   "Dashboard Data: climate_vari_PNA",                    "./dev/data/data/climate_vari_PNA.csv"))
jsons.append(make_json("data",       "climate_vari_SOI",                   "Dashboard Data: climate_vari_SOI",                    "./dev/data/data/climate_vari_SOI.csv"))

print "writing file.json"
with open("file.json", "w") as f:
    f.write("[\n")
    f.write(",\n".join(jsons))
    f.write("\n]\n")

print "importing file.json"
os.system("drush ne-import < file.json")

print "cleaning up"
os.remove("file.json")
